# Generated by Django 4.1 on 2023-03-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_store_code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=0),
        ),
    ]
