# Generated by Django 4.1 on 2023-03-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_product_expiry_date_product_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
