# Generated by Django 4.1 on 2023-03-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_store_code',
            field=models.IntegerField(null=True),
        ),
    ]
